### ISSUE TITLE
使用android12手机调试mqtt

### ISSUE THREAD

**Issue by Zhangzhenguo-git** [lidongRebirth/MQTTDemo#1]
在安卓12的手机上使用mqtt  报一下错误   按照要求修改了，还是报一下错误    Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by lidongRebirth** [comment]
问题已解决，原库未做兼容，已经service部分代码下载至本地并进行了更改
